query PortfolioItems {
  portfolioItemCollection {
    items {
      sys {
        id
      }
      title
      slug
      pageContent
      imagesCollection {
        items {
          url
          fileName
        }
      }
    }
  }
}
